# Envía mensaje IR personalizado

int32 code              # Código IR (0-7)
int32 front_strength    # Intensidad frontal (0-64)
int32 left_strength     # Intensidad izquierda (0-64)
int32 right_strength    # Intensidad derecha (0-64)
int32 rear_strength     # Intensidad trasera (0-64)
---
bool success
string message
