# Información del sistema del Sphero RVR

# Versión de aplicación principal
uint16 app_major
uint16 app_minor
uint16 app_revision

# Versión de bootloader
uint16 bootloader_major
uint16 bootloader_minor
uint16 bootloader_revision

# Información de hardware
uint8 board_revision
string mac_address
string sku
uint64 uptime_ms

# Información de procesadores
string processor_1_name
string processor_2_name
